### ISSUE TITLE
fixed option malfunction

### ISSUE THREAD

**Issue by FreyaStein** [mpieva/quicksand#5]
Hi there, 

Whenever I try to run Quicksand with the --fixed option the bedfiltering does not run the bedfilterbam workflow on the fixed referenced ending with "-" in the ReadsBedfiltered and PostBedCoveredBP output columns.

I have tested the samples with different fixed references. Also, when running on the "best" option, these taxa output/ have bed filtered reads. 

best wishes and thank you in advance, 
Freya

**Comment by merszym** [comment]
@FreyaStein The feature will be available soon (#8), just doing some final tests to make sure that everything works as intended :)
